/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moniac;

import java.awt.Graphics;

/**
 *
 * @author dave
 */
public class TileDetailPanel extends javax.swing.JPanel
{
    Tile tile;
    
    /**
     * Creates new form LocationDetailPanel
     */
    public TileDetailPanel()
    {
        initComponents();
    }

    public void setTile( Tile tile )
    {
        if( tile == null )
            return;
        
        this.tile = tile;

        update();
    }

    public void update()
    {
        if( tile == null )
            return;
        
        StringBuilder text = new StringBuilder();
        
        for( Human agent : tile.getPeople() )
        {
            text.append( agent.getClass().getSimpleName()+": "+agent.getPopulation()+"<br/>" );
            text.append( "Food: "+agent.getFood()+"<br/>" );
            text.append( "Satiation: "+agent.getSatiation()+"<br/>" );
        }
        
        for( Resource resource: tile.getResources() )
        {
            text.append( resource.getName()+": "+resource.getQuantity()+"<br/>" );
        }
        
        detailsText.setText( text.toString() );
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailsText = new javax.swing.JTextPane();

        detailsText.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(detailsText);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane detailsText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
